In [1]:
# 실습 Leader
# 1. 
import numpy as np
a1 = np.zeros((3,4))
a1_2 = np.full((3,4), 5)
print("문제1:", a1, a1_2, sep="\n")

#2. 
a2 = np.arange(0,21,2)
print("\n문제2:", a2)

#3.
a3 = np.random.rand(2,3)
print("\n문제3:", a3)

#4.
a4 = np.random.normal(100, 20, 6)
print("\n문제4:", a4)

#5. 
a5 = np.arange(1,21).reshape(4,5)
print("\n문제5:", a5)

#6. 
a6 = np.linspace(0,1,12).reshape(3,4)
print("\n문제6:", a6)

#7.
a7 = np.random.randint(0,100, (10,10))
a7_eye = np.eye(10)
a7_eye = a7 + a7_eye
print(a7_eye)



문제1:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]

문제2: [ 0  2  4  6  8 10 12 14 16 18 20]

문제3: [[0.19430794 0.24717907 0.19906124]
 [0.1638445  0.36272293 0.29196635]]

문제4: [ 80.70719273  67.00038273 118.38355702  91.9854728  121.40305692
  92.76978927]

문제5: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

문제6: [[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]]
[[  1.  33.  41.  28.  28.  60.  89.  63.  59.  54.]
 [ 72. 100.  33.  54.  70.  36.  53.  55.  96.  55.]
 [ 76.   8.  85.  73.  83.  98.   1.  49.  87.  16.]
 [ 98.  63.  65.  14.  80.  35.  84.  62.  53.  49.]
 [ 68.  74.  62.  63.  24.  12.   4.   5.  46.  51.]
 [  1.  19.  31.  26.  81.  28.  73.  23.  93.  45.]
 [ 53.   2.  95.  15.  52.  75.  85.  82.  50.  30.]
 [ 67.  15.  51.  24.  22.  67.  16.  88.  72.  81.]
 [  9.   0.   8.  69.  25.  61.  90.  46.  95.  42.]
 [ 1

In [5]:
# 실습 2 (Leader)

# 1.
arr = np.arange(10,30,2)
print(arr)
ans = arr[[1,3,5]]
print(ans)
print()

# 2.
arr = np.arange(1,10).reshape(3,3)
print(arr)
arr[[0,1,2],[0,1,2]]
print()
# 3.
arr = np.arange(1,13).reshape(3,4)
print(arr)
arr[:, -1] = -1
print(arr)
print()

[10 12 14 16 18 20 22 24 26 28]
[12 16 20]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3 -1]
 [ 5  6  7 -1]
 [ 9 10 11 -1]]


In [8]:
# 4.
arr = np.arange(1,17).reshape(4,4)
print("행 역순:", arr[::-1])
print("열 역순:", arr[:,::-1])

행 역순: [[13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
열 역순: [[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]
 [16 15 14 13]]


In [14]:
# 5.
arr = np.arange(1,21).reshape(4,5)
print(arr)
arr_copied = arr[1:3, 1:4].copy()
print(arr_copied)

# 6.
arr = np.array([[4,9,12,7],[10,15,18,3],[2,14,6,20]])
arr_bool = arr[(arr % 2 == 0) & (arr >=10)]
print(arr_bool)

# 7.
arr = np.arange(1,26).reshape(5,5)
result = arr[[1,3]]
result[:,[4,0,2]]
print(result)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[ 7  8  9]
 [12 13 14]]
[12 10 18 14 20]
[[ 6  7  8  9 10]
 [16 17 18 19 20]]


In [18]:
# 8.
arr = np.array([[10,20,30],[55,65,75],[40,45,50],[70,80,90],[15,25,35]])
arr[arr[: ,0] >= 50]


array([[55, 65, 75],
       [70, 80, 90]])

In [19]:
# 9.
arr = np.arange(1,17).reshape(4,4)
arr[[0,1,2,3],[1,3,0,2]]

array([ 2,  8,  9, 15])

In [21]:
# 10.
arr3d = np.arange(24).reshape(2,3,4)
print(arr3d)

arr3d[:, :, 1]

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[ 1,  5,  9],
       [13, 17, 21]])

In [24]:
arr = np.random.randint(0,10,(4,4))
print(arr)
arr_r = [arr[i, i]for i in range(4)]
print(arr_r)
arr_r2 = [arr[i,3-i]for i in range(4)]
print(arr_r2)


[[0 1 5 9]
 [1 4 6 0]
 [3 2 9 4]
 [1 2 0 1]]
[np.int32(0), np.int32(4), np.int32(9), np.int32(1)]
[np.int32(9), np.int32(6), np.int32(2), np.int32(1)]


In [ ]:
# 종합 실습 (Leader)
# 1.
a1= np.arange(25).reshape(5,5)
print(a1[2])
print(a1[:,2])

# 2.
import random
a2 = np.random.randint(0,100, (10,10))
print()
print(a2[::2])

# 3.
a3 = np.arange(50).reshape(5,10)
print(a3[1:4, 2:7])

[0. 0. 0. 0.]
[0. 0. 0.]

[ 0  4  8 12 16 20]


In [30]:
# 4.
a4 = np.random.randint(0,10,(4,4))
answer = []
answer2 = []
for i in range(4):
    answer.append(a4[i][i])
    answer2.append(a4[i][3-i])
print("주대각선:\n", answer)
print("부대각선:\n", answer2)
print()

# 5.
a5 = np.random.randint(0,10,(3,4,5))
print(a5[1,0,-1])


주대각선:
 [np.int32(6), np.int32(2), np.int32(4), np.int32(2)]
부대각선:
 [np.int32(7), np.int32(7), np.int32(4), np.int32(7)]

2


In [32]:
# 6.
a6 = np.arange(35,75).reshape(10,4)
print(a6)

# 7.
a7 = a6[::-1]
print(a7)

# 8.
a8 = a6[1:-1,2:]
print(a8)

[[35 36 37 38]
 [39 40 41 42]
 [43 44 45 46]
 [47 48 49 50]
 [51 52 53 54]
 [55 56 57 58]
 [59 60 61 62]
 [63 64 65 66]
 [67 68 69 70]
 [71 72 73 74]]
[[71 72 73 74]
 [67 68 69 70]
 [63 64 65 66]
 [59 60 61 62]
 [55 56 57 58]
 [51 52 53 54]
 [47 48 49 50]
 [43 44 45 46]
 [39 40 41 42]
 [35 36 37 38]]
[[41 42]
 [45 46]
 [49 50]
 [53 54]
 [57 58]
 [61 62]
 [65 66]
 [69 70]]


In [36]:
# 9.
a9 = np.random.randint(1,51,(5,6))
mask = a9 % 2 == 0
a9_as = a9[mask]
print(a9_as)

# 10. 
a10 = np.arange(100).reshape(10,10)
# selcted_row = arr[[1,3,5]] 도 가능하다
print(a10)


a10_as = a10[[1,3,5]][:,[2,4,6]]
print(a10_as)

# 11.
a11 = np.random.randint(0,10,15)
even_idx_value = a11[::2]
print(even_idx_value)
mask = even_idx_value >= 5
print(mask)
all = even_idx_value[mask]
print(all)

[16 10  6 20 26 28 30 12 38 14 42 16]
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
[[12 14 16]
 [32 34 36]
 [52 54 56]]
[1 1 9 7 6 1 6 9]
[False False  True  True  True False  True  True]
[9 7 6 6 9]
