In [1]:
import numpy as np
arr = np.array([1,2,3,4])
a1 = arr + 3
print(a1)

[4 5 6 7]


In [2]:
arr = np.array([[5,10],
                [15,20]])
a2 = arr * -1
print(a2)

[[ -5 -10]
 [-15 -20]]


In [3]:
arr1 = np.array([2,4,6])
arr2 = np.array([1,2,3])
a3_1 = arr1 * arr2
a3_2 = arr2 / arr1
print("곱셈 값:", a3_1)
print("나눗셉 값:", a3_2)


곱셈 값: [ 2  8 18]
나눗셉 값: [0.5 0.5 0.5]


In [5]:
arr = np.array([[1,2,3],
                [4,5,6]])
mul = np.array([10,100]).reshape(-1,1)
a5 = arr * mul
print(a5)


[[ 10  20  30]
 [400 500 600]]


In [6]:
arr = np.array([[10,20],
                [30,40],
                [50,60]])
add = np.array([100,200,300]).reshape(-1,1)
a6 = arr + add
print(a6)

[[110 120]
 [230 240]
 [350 360]]
