In [2]:
import numpy as np
arr = np.array([1,2,3,4])
a1 = arr + 3
print(a1)

[4 5 6 7]


In [2]:
arr = np.array([[5,10],
                [15,20]])
a2 = arr * -1
print(a2)

[[ -5 -10]
 [-15 -20]]


In [3]:
arr1 = np.array([2,4,6])
arr2 = np.array([1,2,3])
a3_1 = arr1 * arr2
a3_2 = arr2 / arr1
print("곱셈 값:", a3_1)
print("나눗셉 값:", a3_2)


곱셈 값: [ 2  8 18]
나눗셉 값: [0.5 0.5 0.5]


In [5]:
arr = np.array([[1,2,3],
                [4,5,6]])
mul = np.array([10,100]).reshape(-1,1)
a5 = arr * mul
print(a5)


[[ 10  20  30]
 [400 500 600]]


In [6]:
arr = np.array([[10,20],
                [30,40],
                [50,60]])
add = np.array([100,200,300]).reshape(-1,1)
a6 = arr + add
print(a6)

[[110 120]
 [230 240]
 [350 360]]


In [9]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
as6 = np.cumsum(arr, axis=1)
as6_1 = np.cumsum(arr, axis=0)
as6_2 = np.cumprod(arr, axis=1)
as6_3 = np.cumprod(arr, axis=0)
print("행 단위 누적 합:\n", as6)
print("열 단위 누적 합:\n", as6_1)
print("행 단위 누적 곱:\n", as6_2)
print("열 단위 누적 곱:\n", as6_3)


arr8 = np.random.randint(0,101,size = 10)
print(arr8)
print(np.where(arr8 >= 50, arr8, 50))


행 단위 누적 합:
 [[ 1  3  6]
 [ 4  9 15]]
열 단위 누적 합:
 [[1 2 3]
 [5 7 9]]
행 단위 누적 곱:
 [[  1   2   6]
 [  4  20 120]]
열 단위 누적 곱:
 [[ 1  2  3]
 [ 4 10 18]]
[70 74 75 78 29 87 26 75 77 18]
[70 74 75 78 50 87 50 75 77 50]


In [11]:
arr9 = np.array([[5,50,95],
                 [20,75,10],
                 [60,30,85]])
result = np.where(arr9 >= 70, "A",
                  np.where(arr9 >= 30, "B", "C"))
print(result)

[['C' 'B' 'A']
 ['C' 'A' 'C']
 ['B' 'B' 'A']]
