## 02. numpy

### 2-1. numpy 배열 연산

In [1]:

import numpy as np

# 배열 간 연산 (1차원)
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
print(a1 + a2)
print(a1 - a2)

[5 7 9]
[-3 -3 -3]


In [3]:
# 배열 간 연산 (2차원)
a1 = np.arange(1,5).reshape(2,2)
a2 = np.arange(11,15).reshape(2,2)
print(a1)
print(a2)
print(a1 + a2)
print(a2 - a1)


[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[12 14]
 [16 18]]
[[10 10]
 [10 10]]


In [4]:
# 배열과 스칼라 연산 (1차원)
a1 = np.array([1,2,3,4])
print(a1 + 10)
print(a1 * 2)


[11 12 13 14]
[2 4 6 8]


In [5]:
# 배열과 스칼라 연산(2차원)
a1 = np.arange(1,5).reshape(2,2)
a2 = np.arange(11,15).reshape(2,2)
print(a1)
print(a2)
print(a1 + 5)
print(a2 * 3)
print(a2 / 2)

[[1 2]
 [3 4]]
[[11 12]
 [13 14]]
[[6 7]
 [8 9]]
[[33 36]
 [39 42]]
[[5.5 6. ]
 [6.5 7. ]]


In [7]:
# 배열의 구조가 다를 경우
a1 = np.array([1,2])
a2 = np.array([1,2,3])
# print(a1 + a2) # 에러가 뜬다: ValueError

In [8]:
# 브로드캐스팅
# 자동으로 배열의 크기를 확장 -> 서로 다른 크기의 배열 간 연산을 가능하게 하는 기능
# 1. 두 배열의 차원을 뒤(낮은 차원)에서부터 비교
# 2. 크기가 같거나
# 3. 한 쪽이 1인 경우 확장이 가능

a1= np.array([[1,2,3],
              [4,5,6]]) # (2,3)
a2= np.array([10,20,30]) # 길이가 3인 1차원 배열 (3, )

# 1차원 길이 3
[10,20,30]

# 2차원으로 변형 (1,3)
[[10,20,30]]

# 2차원의 행이 2 -> 2로 확장
[[10,20,30],
 [10,20,30]]
print(a1 + a2)

[[11 22 33]
 [14 25 36]]


In [ ]:
# 브로드캐스팅 예제
a1 = np.array([[1],[2],[3]]) # (3,1)
a2 = np.array([10,20,30]) # (3, )

# a2: (3, )-> (1,3) 변형
[[10,20,30]]

# a1과 a2를 비교 -> (3,1), (1,3)
[[1,1,1],[2,2,2],[3,3,3]]
[[10,20,30],[10,20,30],[10,20,30]]

print(a1 + a2)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [6]:
# 실습
# 1.
import numpy as np
arr  = np.array([1,2,3,4])
a1 = arr + 3
print(a1)
print()

# 2.
arr = np.array([[5,10],
                [15,20]])
a2 = arr * -1
print(a2)
print()

# 3.
arr1 = np.array([2,4,6])
arr2 = np.array([1,2,3])
a3_1 = arr1 * arr2
a3_2 = arr1 / arr2
print("두 배열의 곱셈 결과:", a3_1)
print("두 배열의 나눗셈 결과:", a3_2)

[4 5 6 7]

[[ -5 -10]
 [-15 -20]]

두 배열의 곱셈 결과: [ 2  8 18]
두 배열의 나눗셈 결과: [2. 2. 2.]


In [8]:
# 4.
arr = np.array([[95,97],
                [80,85]])
a4 = arr + (100 - arr)
print(a4)
print()

# 5. 
arr = np.array([[1,2,3], [4,5,6]])
mul = np.array([10,100]).reshape(-1,1)
a5 = arr * mul
print(a5)

[[100 100]
 [100 100]]

[[ 10  20  30]
 [400 500 600]]


In [9]:
# 6.
arr = np.array([[10,20],
                [30,40],
                [50,60]])
add = np.array([100,200,300]).reshape(-1,1)
a6 = arr + add
print(a6)

[[110 120]
 [230 240]
 [350 360]]


### 2-2. 통계 함수 및 집계 연산

In [10]:
a = np.array([[1,2,3], [4,5,6]])

print("원소의 합:" , np.sum(a))
print("원소의 평균:", np.mean(a))
print("표준편차:", np.std(a))
print("최대값:", np.max(a))
print("최소값:", np.min(a))
print("최대값의 인덱스:", np.argmax(a))
print("최소값의 인덱스:", np.argmin(a))

원소의 합: 21
원소의 평균: 3.5
표준편차: 1.707825127659933
최대값: 6
최소값: 1
최대값의 인덱스: 5
최소값의 인덱스: 0


In [12]:
# 축 (axis) 단위 연산
# axis = 0 -> 가장 높은 차원 기준-> 행 기준
 # 행 기준 = 행을 따라 연산 = 행을 증가시키며 연산
# axis = 1 -> 그 다음 차원 기준-> 열 기준
 # 열 기준 = 열을 따라 연산 = 열을 증가시키며 연산

a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print("행기준합", np.sum(a, axis=0))
print("열기준합", np.sum(a, axis=1))
print("행기준평균", np.mean(a, axis=0))
print("행기준평균", np.mean(a, axis=1))

행기준합 [12 15 18]
열기준합 [ 6 15 24]
행기준평균 [4. 5. 6.]
행기준평균 [2. 5. 8.]


In [13]:
# 누적 연산
arr = np.array([1,2,3,4])
print(np.cumsum(arr))
print(np.cumprod(arr))


[ 1  3  6 10]
[ 1  2  6 24]


In [18]:
# 실습 2
# 1.
arr = np.array([5,10,15,20])
as1 = np.sum(arr)
as1_1 = np.mean(arr)
print("전체합계:", as1)
print("전체평균:", as1_1)
print()

# 2.
arr = np.array([[3,7,1],
                [9,2,8]])
as2 = np.max(arr)
as2_1 = np.min(arr)
print("전체 최소값:", as2)
print("전체 최대값:", as2_1)
print()

#3.
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
as3 = np.sum(arr, axis=0)
as3_1 = np.sum(arr, axis=1)
print("각 행의 합계:", as3)
print("각 열의 합계:", as3_1)



전체합계: 50
전체평균: 12.5

전체 최소값: 9
전체 최대값: 1

각 행의 합계: [12 15 18]
각 열의 합계: [ 6 15 24]


In [27]:
# 4.
arr = np.array([[10,20],
                [30,40],
                [50,60]])
as4 = np.mean(arr, axis=0)
as4_1 = np.mean(arr, axis=1)
print("행별 평균:", as4)
print("열별 평균:", as4_1)
print()

# 5.
arr = np.array([2,4,4,4,5,5,7,9])
as5 = arr.std()
as5_1 = arr.mean()
as5_2 = arr - as5_1
print("표준편차:", as5)
print("편차 배열:", as5_2)
print()

# 6.
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
as6 = np.cumsum(arr, axis=0)
as6_1 = np.cumsum(arr, axis=1)
as6_2 = np.cumprod(arr, axis=0)
as6_3 = np.cumprod(arr, axis=1)
print("행 단위 누적 합:\n", as6)
print("열 단위 누적 합:\n", as6_1)
print("행 단위 누적 곱:\n", as6_2)
print("열 단위 누적 곱:\n", as6_3)

행별 평균: [30. 40.]
열별 평균: [15. 35. 55.]

표준편차: 2.0
편차 배열: [-3. -1. -1. -1.  0.  0.  2.  4.]

행 단위 누적 합:
 [[1 2 3]
 [5 7 9]]
열 단위 누적 합:
 [[ 1  3  6]
 [ 4  9 15]]
행 단위 누적 곱:
 [[ 1  2  3]
 [ 4 10 18]]
열 단위 누적 곱:
 [[  1   2   6]
 [  4  20 120]]


### 2-3. 논리 연산과 조건 연산

In [29]:
# np.where()
# 조건 기반 선택 함수

arr = np.array([10,20,30,40,50])
result = np.where(arr > 30, "High", "Low")
result

array(['Low', 'Low', 'Low', 'High', 'High'], dtype='<U4')

In [ ]:
arr = np.array([10,20,30,40,50])
# 조건만 넣을 경우 조건을 만족하는 원소의 인덱스를 반환
result = np.where(arr>30)
print(result)
print(arr[result]) # Fancy Indexing

(array([3, 4]),)
[40 50]


In [36]:
# 논리 연산
# and : & - 모든 조건이 True여야  True
# or : | - 조건 중 하나라도 True면 True
# not : ~ - True-> False, Fale -> True로 전환

# and연산 (&)
arr = np.array([10,20,30,40,50])
mask = (arr > 10) & (arr < 50)
print(mask)
print("&연산", arr[mask])
print()
# or연산 (|)
mask_or = (arr < 20) | (arr > 40)
print("|연산", arr[mask_or])
print()
# not연산자 (~)
mask_not = ~(arr > 30)
print("~연산", arr[mask_not])

[False  True  True  True False]
&연산 [20 30 40]

|연산 [10 50]

~연산 [10 20 30]


In [55]:
# 실습3
# 1. 
arr = np.array([5,12,18,7,30,25])
an1 = arr[(arr > 10) & (arr <20)]
print(an1)
print()
# 2.
arr = np.array([10,15,20,25,30,35])
an2 = arr[(arr <= 15) | (arr >= 30)]
print(an2)
print()
# 3.
arr = np.array([3,8,15,6,2,20])
arr[arr >= 10] = 0
print(arr)
print()

# 4.
arr = np.array([7,14,21,28,35])
an4 = np.where(arr >= 20, "High", "Low")
print(an4) 

[12 18]

[10 15 30 35]

[3 8 0 6 2 0]

['Low' 'Low' 'High' 'High' 'High']


In [62]:
# 5.
arr = np.arange(0,10)
an5 = np.where(arr % 2 == 1, arr * 10, arr)
print(an5)
print()
# 6.
arr = np.array([[10,25,30],
                [40,5,15],
                [20,35,50]])
an6 = arr[(arr >= 20) & (arr <= 40)]
print(an6)
print()
# 7.
arr = np.array([1,2,3,4,5,6])
an7 = arr[arr % 3 != 0]
print(an7)

[ 0 10  2 30  4 50  6 70  8 90]

[25 30 40 20 35]

[1 2 4 5]


In [60]:
# 8.
arr = np.arange(0,100).reshape(10,10)
an8 = np.where(arr >= 50, arr, 50)
print("8번 결과:\n", an8)
print()
# 9.
arr = np.array([[5,50,95],
                [20,75,10],
                [60,30,85]])
an9 = np.where(arr >= 70, "A", np.where(arr >= 30, "B", "c"))
print(an9)


8번 결과:
 [[50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50 50 50 50]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

[['c' 'B' 'A']
 ['c' 'A' 'c']
 ['B' 'B' 'A']]


### 2-4. 행렬 곱셈
- 두 행렬을 곱해서 새로운 행렬을 생성하는 연산
- 첫 번째 행렬의 열수와 두 번째 행렬의 행수가 같아야 곱셈이 가능함
- np.dot(), np.matmul() -> 사용

In [ ]:
# np.dot(a,b): 배열의 내적 연산
# 스칼라 연산 (OD)
a = np.array(3)
b = np.array(4)
print(np.dot(a,b))


In [ ]:
# 1차원 배얄 간 연산 -> 내적
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.dot(a,b)) # 1*4 + 2*5 + 3*6

# 물건 구매
# 데이터분석에서 벡터랑 배열
c = [1000,2000,5000,10000]
d = [10,3,5,7]
print(np.dot(c,d))


In [ ]:
# 2차원 배열간 연산 -> 행렬 곱셈
a = np.array([[1,2,3],[4,5,6]]) # (2,3)
b = np.array([[1,2],[3,4],[5,6]]) # (3,2)
print(np.dot(a,b))


In [ ]:
# np.matmul(a,b)
# Matrix Multiplication
# 스칼라 연산 시도시 에러
a = np.array(3)
b = np.array(4)
# print(np.matmul(a,b))

In [ ]:
# 1차원 배열간 연산 -> 내적
a = np.array([1,2])
b = np.array([3,4])
print(np.matmul(a,b)) # 1*3 + 2*4


In [64]:
# 2차원 배열간 연산 -> 행렬 곱셈
a = np.array([[1,2,3],
              [4,5,6]]) # (2,3)
b = np.array([[1,2],
              [3,4],
              [5,6]]) # (3,2)
print(np.matmul(a,b)) # 1*1+2*3+3*5=22 1*2+2*4+3*6=28

# 2차원 * 1차원 간 연산
c = np.array([[1,2],[3,4]]) # (2,2)
d = np.array([5,6]) # (2,)
print(np.matmul(c,d))

# @ 연산자
e = np.array([[1,2,3]])
f = np.array([[1,2],
              [3,4],
              [5,6]])
print(np.matmul(e,f))
print(e @ f)

[[22 28]
 [49 64]]
[17 39]
[[22 28]]
[[22 28]]


In [73]:
# 실습 4
# 1.
a = np.arange(1,10).reshape(3,3)
b = np.full((3,2),2)
print(a)
print(b)
print(a @ b)
print()
# 2.
i = np.eye(4,dtype=int)
m = np.random.randint(0,10, (4,4))
print(m)
print(i @ m)
print()
# 3.
x = np.ones((2,5), dtype=int)
y = np.arange(5,15).reshape(5,2)
print(x)
print(x @ y)
print()
# 4.
c = np.random.randint(0,6, (3,2))
d = np.random.randint(0,6,(2,3))
ans4 = c @ d
print(ans4)
print("shape=", ans4.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2]
 [2 2]
 [2 2]]
[[12 12]
 [30 30]
 [48 48]]

[[5 0 1 7]
 [6 0 9 1]
 [8 6 7 3]
 [7 6 7 7]]
[[5 0 1 7]
 [6 0 9 1]
 [8 6 7 3]
 [7 6 7 7]]

[[1 1 1 1 1]
 [1 1 1 1 1]]
[[45 50]
 [45 50]]

[[ 5 10  0]
 [15 18  0]
 [20 23  0]]
shape= (3, 3)
