## 03. NumPy
### 3-1. 배열의 형태 변형과 차원 확장/축소

In [2]:
import numpy as np


In [3]:
# array.ravel()
# - 다차원 배열을 1차원 배열로 펼침
# - 결과를 view로 반환(view 변경 시 원본도 변경)

a = np.array([[1,2,3],[4,5,6]])
print(a)

flat = a.ravel()
print(flat)

flat[2] = 100
print(flat)
print(a)

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]
[  1   2 100   4   5   6]
[[  1   2 100]
 [  4   5   6]]


In [6]:
# array.flatten()
# - 다차원 배열을 1차원 배열로 펼침
# - 결과를 복사본으로 반환 (복사본 변경 시 원본은 변경되지 않음)

a = np.array([[[1,2], [3,4], [5,6], [7,8]]])
print(a)
flat = a.flatten()
print(flat)
flat[4] = 0
print(flat)
print(a)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]
[1 2 3 4 5 6 7 8]
[1 2 3 4 0 6 7 8]
[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [10]:
# np.expand_dims(a, axis)
# 지정한 위치에 차원 추가 (차원 확장)
# 추가되는 차원은 1
a = np.array([[1,2,3],[4,5,6]])
print("원본:", a.shape)

#axis = 0
a0 = np.expand_dims(a, axis=0)
print("a0", a0.shape)
print("a0", a0)

# axis = 1
a1 = np.expand_dims(a, axis=1)
print("a1", a1.shape)
print("a1", a1)

# axis = 2
a2 = np.expand_dims(a, axis=2)
print("a2", a2.shape)
print("a2", a2)

원본: (2, 3)
a0 (1, 2, 3)
a0 [[[1 2 3]
  [4 5 6]]]
a1 (2, 1, 3)
a1 [[[1 2 3]]

 [[4 5 6]]]
a2 (2, 3, 1)
a2 [[[1]
  [2]
  [3]]

 [[4]
  [5]
  [6]]]


In [ ]:
# np.sqeeze(a, axis)
#  - 배열에서 크기가 1인 차원을 제거해주는 함수(차원 축소)
a = np.array([[[[1],[2],[3]]], [[[1],[2],[3]]]])
print(a.shape)

s = np.squeeze(a)
print(s)
print(s.shape)

(2, 1, 3, 1)
[[1 2 3]
 [1 2 3]]
(2, 3)


In [ ]:
# axis 지정하는 경우
a2 = np.zeros((1,4,1,2))
print(a2.shape)

s1 = np.squeeze(a2, axis=0)
print(s1.shape) # (4,1,2)

s2 = np.squeeze(a2, axis=2)
print(s2.shape) # (1,4,2)

# 차원의 크기가 1이 아닌 차워은 제거할 수 없다
# s3 = np.squeeze(a2, axis=1) # ValueError


(1, 4, 1, 2)
(4, 1, 2)
(1, 4, 2)


In [17]:
# np.unique()
# - 배열에서 중복된 요소를 제거
a = np.array([1,1,1, 5,5, 2,2,2,2, 4,4,4, 3,3,3])
u1 = np.unique(a) # 고유값의 오름차순 배열 반환
print(u1)

u2, idx, inv, cnt = np.unique(a, return_index=True, return_inverse=True, return_counts=True)
print("인덱스:", idx)
print("원본의 교육값 인덱스:", inv)
print("값의 등장 횟수:", cnt)


[1 2 3 4 5]
인덱스: [ 0  5 12  9  3]
원본의 교육값 인덱스: [0 0 0 4 4 1 1 1 1 3 3 3 2 2 2]
값의 등장 횟수: [3 4 3 3 2]


In [31]:
# 실습 1 
# 1.
arr = np.array([[10,20],[30,40],[50,60]])
an1_1 = arr.ravel()
an1_2 = arr.flatten()
print("문1.ravel:", an1_1)
print("문2.flatten:", an1_2)
arr[0,0] = 999
print("\n변경 후 arr:\n", arr)
print("ravel:", an1_1)
print("flatten:", an1_2)
print()

# 2.
img = np.random.rand(32,32)
an2 = np.expand_dims(img, axis=0)
print(img)
print(an2.shape)

문1.ravel: [10 20 30 40 50 60]
문2.flatten: [10 20 30 40 50 60]

변경 후 arr:
 [[999  20]
 [ 30  40]
 [ 50  60]]
ravel: [999  20  30  40  50  60]
flatten: [10 20 30 40 50 60]

[[0.53149983 0.96166722 0.96014775 ... 0.24977374 0.42730028 0.30877365]
 [0.50987292 0.49033568 0.80112489 ... 0.89055821 0.63658168 0.25976234]
 [0.15795887 0.21673158 0.24640269 ... 0.35907295 0.29989137 0.06794158]
 ...
 [0.16976008 0.23956179 0.92083475 ... 0.43583209 0.44331516 0.94983523]
 [0.59126073 0.95637898 0.57288886 ... 0.21105493 0.00790977 0.85731651]
 [0.20046273 0.67077198 0.68054857 ... 0.09369969 0.1510633  0.52567775]]
(1, 32, 32)


In [27]:
# 3.
img = np.random.randint(0,255,(1,28,28,1))
an3 = np.squeeze(img)
print(an3.shape)
print()
# 4.
arr = np.array([[3,1,2,2],
                [1,2,3,1],
                [2,2,1,4]])
an4_f = arr.flatten()
an4_uq = np.unique(an4_f)
an4 = an4_uq.reshape(1, len(an4_uq))
print("flat:", an4_f)
print("unique:", an4_uq)
print(an4)

(28, 28)

flat: [3 1 2 2 1 2 3 1 2 2 1 4]
unique: [1 2 3 4]
[[1 2 3 4]]


In [32]:
# 5.
arr = np.array([[[1],[3],[2],[1],[3],[2],[3],[1],[2],[3]]])
an5 = np.squeeze(arr)
print(an5)
an5_uq = np.unique(an5)
print(an5_uq)
print()
# 6.
arr = np.array([[[0,1,2,3],[1,2,3,4],[2,3,4,5],
                 [3,4,5,6],[4,5,6,7],[5,6,7,8]]])
an6_f = arr.flatten()
an6_uq = np.unique(an6_f)
an6 = an6_uq.reshape(len(an6_uq),1)
print("flat:", an6_f)
print("unique:", an6_uq)
print(an6)



[1 3 2 1 3 2 3 1 2 3]
[1 2 3]

flat: [0 1 2 3 1 2 3 4 2 3 4 5 3 4 5 6 4 5 6 7 5 6 7 8]
unique: [0 1 2 3 4 5 6 7 8]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


### 3-2. 배열의 결합과 분리

In [37]:
# np.concatenate()
# 배열 시퀀스를 결합
# 기존 구조 안에서 결합
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

result1 = np.concatenate((a,b), axis=0) # 행
print(result1) 
print(result1.shape)

# 결합이 불가 -> 결합하는 axis를 제외한 나머지 차원이 같아야 함
# result2 = np.concatenate((a,b), axis=1)

c = np.array([[7],[8],[9]])
result3 = np.concatenate((result1,c), axis=1)
print(result3)
print(result3.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)
[[1 2 7]
 [3 4 8]
 [5 6 9]]
(3, 3)


In [39]:
# np.stack()
# 새로운 차원을 추가하면서 결합
a = np.array([1,2,3])
b = np.array([4,5,6])

# axis = 0
s1 = np.stack((a,b), axis=0)
print(s1)
print(s1.shape)

# axis = 1
s2 = np.stack((a,b), axis=1)
print(s2)
print(s2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [ ]:
# np.hstack()
# - 열 방향(가로)로 결합
a = np.array([1,2,3])
b = np.array([4,5,6])

h = np.hstack((a,b))
print(h)

# np.vstack()
# - 행 방향(세로)로 결합
v= np.vstack((a,b))
print(v)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [43]:
# np.split()
# - 배열을 여러개의 하위 배열로 분할
a = np.arange(9)
s = np.split(a, 3)
print(a)
print(s)
print(s[0])
print(s[1])
print(s[2])

# 같은 크기로만 나눌 수 있음

# s2 = np.split(a, 4)



[0 1 2 3 4 5 6 7 8]
[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]
[0 1 2]
[3 4 5]
[6 7 8]


In [48]:
a = np.arange(16).reshape(4,4)
print(a)

s1 = np.split(a, [1,3])
print(s1)
for part in s1:
    print(s1)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]
[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [ ]:
# 실습2
# 1.
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
an1 = np.concatenate((a,b), axis=0)
print(an1)
print()

# 2.
a = np.arange(12)
an2 = np.split(a,3)
print(an2)
print()
#3.
a = np.array([1,2])
b = np.array([3,4])
c = np.array([5,6])
an3 = np.stack((a,b,c), axis=0)
print(an3)
print("shape:", an3.shape)

[[1 2]
 [3 4]
 [5 6]]

[array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

[[1 2]
 [3 4]
 [5 6]]
shape: (3, 2)


In [55]:
# 4.
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
an4 = np.stack((a,b), axis=0)
print(an4)
print("shape:", an4.shape)
print()
#5.
arr = np.arange(8)
an5 = np.split(arr,(2,5))
print(an5)
print()
# 6.
a = np.ones((2,3))
b = np.zeros((2,3))
an6_1 = np.stack((a,b), axis=0)
an6_2 = np.stack((a,b), axis=1)
print("\naxis=0:\n", an6_1)
print("\naxis=1:\n", an6_2)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
shape: (2, 2, 3)

[array([0, 1]), array([2, 3, 4]), array([5, 6, 7])]


axis=0:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]

axis=1:
 [[[1. 1. 1.]
  [0. 0. 0.]]

 [[1. 1. 1.]
  [0. 0. 0.]]]


### 3-3. 배열의 정렬

In [ ]:
# np.sort(array)
# 정렬된 복사본 반환
# array.sort()
# 원본 배열을 정렬

# 1차원 배열
a = np.array([3,1,4,2])

# 정렬한 배열을 반환
s = np.sort(a)
print(s)
print(a)

# 원본을 정렬
a.sort()
print(a)

# 내림차순: sort한 후 배열을 뒤집어야 함
print(a[::-1])


[1 2 3 4]
[3 1 4 2]
[1 2 3 4]
[4 3 2 1]


In [7]:
# 2차원 배열 정렬
a = ([6,5,4],[3,1,2])
s1 = np.sort(a, axis=0)
print(s1)
s2 = np.sort(a, axis=1)
print(s2)

[[3 1 2]
 [6 5 4]]
[[4 5 6]
 [1 2 3]]


In [8]:
# np.argsort()
# - 정렬 인덱스를 반환

a = np.array([3,5,1,2,4])
idx = np.argsort(a)
print(idx)
print(a[idx])

[2 3 0 4 1]
[1 2 3 4 5]


In [10]:
# 실습 3
# 1.
arr = np.array([7,2,9,4,5])
an1 = np.sort(arr)
print("오름차순:", an1)
print("내림차순:", an1[::-1])
print()
#2.
arr = np.array([[9,2,5],
                [3,8,1]])
an2 = np.sort(arr, axis=1)
print(an2)


오름차순: [2 4 5 7 9]
내림차순: [9 7 5 4 2]

[[2 5 9]
 [1 3 8]]


In [13]:
# 3.
arr = np.array([10,3,7,1,9])
a3_idx = np.argsort(arr)
an3 = arr[a3_idx]
print("정렬 인덱스:", a3_idx)
print("정렬 결과:", an3)
print()
# 4.
arr = np.array([[4,7,2],
                [9,1,5],
                [6,8,3]])
an6 = np.sort(arr, axis=0)
print(an6)

정렬 인덱스: [3 1 2 4 0]
정렬 결과: [ 1  3  7  9 10]

[[4 1 2]
 [6 7 3]
 [9 8 5]]
