## 03. 텐서의 조작

In [2]:
import torch

### 3-1. 인덱싱, 슬라이싱
- numpy와 동일한 방식으로 인덱싱, 슬라이싱 가능

In [8]:
x = torch.tensor([[1,2,3],
                  [4,5,6],
                  [7,8,9]])
print(x[1,1]) # 5
print(x[2,0]) # 7
print(x[0, :]) # 0행 전체
print(x[:, 2]) # 2열 전체
print(x[[0,1,2], [0,1,2]]) # fancy 인덱싱
print(x[x > 5]) # boolean 인덱싱

tensor(5)
tensor(7)
tensor([1, 2, 3])
tensor([3, 6, 9])
tensor([1, 5, 9])
tensor([6, 7, 8, 9])


In [ ]:
x = torch.tensor([10,20,30,40,50])

x[0] = 100
print(x)

# 슬라이싱으로 값을 변경할 시 tensor로 값을 할당
x[1:4] = torch.tensor([200,300,400])
print(x)

tensor([100,  20,  30,  40,  50])
tensor([100, 200, 300, 400,  50])


### 3-2. 텐서의 크기, 모양 변경
- torch.view()

In [6]:
x = torch.randn(4,5)
print(x)
y = x.view(20)
print(y)
z = y.view(5,-1) # -1 -> 자동 계산
print(z)

n = z.view(2, 2, 5)
print(n)

tensor([[ 0.8249, -1.3113,  0.2524,  0.0793, -0.5303],
        [ 0.5217,  1.5876,  0.7559, -0.3587,  0.1026],
        [-0.5705,  0.0902,  0.6587, -0.1790, -0.6619],
        [-0.0601, -0.7072, -0.7467,  0.2192,  0.5554]])
tensor([ 0.8249, -1.3113,  0.2524,  0.0793, -0.5303,  0.5217,  1.5876,  0.7559,
        -0.3587,  0.1026, -0.5705,  0.0902,  0.6587, -0.1790, -0.6619, -0.0601,
        -0.7072, -0.7467,  0.2192,  0.5554])
tensor([[ 0.8249, -1.3113,  0.2524,  0.0793],
        [-0.5303,  0.5217,  1.5876,  0.7559],
        [-0.3587,  0.1026, -0.5705,  0.0902],
        [ 0.6587, -0.1790, -0.6619, -0.0601],
        [-0.7072, -0.7467,  0.2192,  0.5554]])
tensor([[[ 0.8249, -1.3113,  0.2524,  0.0793, -0.5303],
         [ 0.5217,  1.5876,  0.7559, -0.3587,  0.1026]],

        [[-0.5705,  0.0902,  0.6587, -0.1790, -0.6619],
         [-0.0601, -0.7072, -0.7467,  0.2192,  0.5554]]])


### 3-3. 텐서의 숫자값 읽기
- tensor.item(): 스칼라 값 하나만 존재해야 가능

In [8]:
x = torch.rand(2)
print(x)
print(x[0])

print(x[0].item())

tensor([0.4918, 0.3072])
tensor(0.4918)
0.49181896448135376


### 3-4. 차원 죽소 및 증가
#### 차원 축소(제거)
- torch.squeeze(): 크기가 1인 차원을 제거함


In [14]:
t = torch.rand(3, 1, 3)
print(t)
print(t.shape)

ts = torch.squeeze(t)
print(ts)
print(ts.shape)

tensor([[[0.1459, 0.8153, 0.4487]],

        [[0.4836, 0.6114, 0.8478]],

        [[0.0664, 0.1192, 0.9488]]])
torch.Size([3, 1, 3])
tensor([[0.1459, 0.8153, 0.4487],
        [0.4836, 0.6114, 0.8478],
        [0.0664, 0.1192, 0.9488]])
torch.Size([3, 3])


#### 차원 증가(생성)
- torch.unsqueeze(): dim 설정에 따라 차원을 증가시킴
  - dim은 하나의 차원이 추가되는 인덱스
  

In [18]:
t = torch.rand(3, 3, 3)
print(t.shape)

# 0: 가장 상위 차원 -> 3: 가장 하위 차원
ts1 = torch.unsqueeze(t, dim=0)
print(ts1.shape)

ts2 = torch.unsqueeze(t, dim=1)
print(ts2.shape)

ts3 = torch.unsqueeze(t, dim=2)
print(ts3.shape)

ts4 = torch.unsqueeze(t, dim=3)
print(ts4.shape)

torch.Size([3, 3, 3])
torch.Size([1, 3, 3, 3])
torch.Size([3, 1, 3, 3])
torch.Size([3, 3, 1, 3])
torch.Size([3, 3, 3, 1])


#### 3-5. 텐서간 결합
- torh.stack(): 동일한 형식의 텐서를 새롭게 그룹화 함 -> 새로운 차원 생성됨

In [22]:
x = torch.tensor([1, 4])
y = torch.tensor([2, 5])
z = torch.tensor([3, 6])
result = torch.stack([x, y, z])
print(result)

a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])
result = torch.stack([a,b])
print(result)

tensor([[1, 4],
        [2, 5],
        [3, 6]])
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])


- torch.cat(): 데이터를 하나의 텐서로 병합 -> 새로운 차원 생성 X

In [23]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[7, 8], [9, 10]])
result = torch.cat((a,b), dim=1)
print(result)

tensor([[ 1,  2,  7,  8],
        [ 3,  4,  9, 10]])


## 3-6. 텐서 나누기
- torch.chunk(): 텐서를 지정한 계수에 따라 나눔
  - 나누어 떨어지지 않는 경우 -> 마지막 조각의 크기가 달라짐
- torch.spilt():  지정한 사이즈에 따라 나눔
  - 나누어 떨어지지 않는 경우 -> 마지막 조각의 크기가 달라짐
  

In [24]:
t = torch.rand(3, 7)
print(t)

t1, t2, t3 = torch.chunk(t, 3, dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.3747, 0.9545, 0.1914, 0.8799, 0.1219, 0.3498, 0.8571],
        [0.9950, 0.2238, 0.2472, 0.3317, 0.2157, 0.9041, 0.2061],
        [0.5437, 0.7071, 0.6974, 0.2930, 0.5556, 0.8181, 0.5733]])
tensor([[0.3747, 0.9545, 0.1914],
        [0.9950, 0.2238, 0.2472],
        [0.5437, 0.7071, 0.6974]])
tensor([[0.8799, 0.1219, 0.3498],
        [0.3317, 0.2157, 0.9041],
        [0.2930, 0.5556, 0.8181]])
tensor([[0.8571],
        [0.2061],
        [0.5733]])


In [25]:
t= torch.rand(3, 7)
print(t)

# 쪼갤 열의 개수 지정
t1, t2, t3 = torch.split(t, [2, 3, 2], dim=1)
print(t1)
print(t2)
print(t3)

tensor([[0.0447, 0.6008, 0.3384, 0.6704, 0.3454, 0.9965, 0.7509],
        [0.3438, 0.9185, 0.4056, 0.1697, 0.6561, 0.4966, 0.7076],
        [0.9373, 0.9135, 0.6218, 0.1398, 0.3660, 0.2654, 0.4075]])
tensor([[0.0447, 0.6008],
        [0.3438, 0.9185],
        [0.9373, 0.9135]])
tensor([[0.3384, 0.6704, 0.3454],
        [0.4056, 0.1697, 0.6561],
        [0.6218, 0.1398, 0.3660]])
tensor([[0.9965, 0.7509],
        [0.4966, 0.7076],
        [0.2654, 0.4075]])
