# 04. Autograd(자동미분)
- PyTorch는 Tensor의 모든 연산에 대해서 자동 미분이 가능함 
- 자동미분은 역전파에 활요됨
- requires-grad: Tensor의 속성으로, True로 설정해야 자동미분이 가능
- tensor.backWard(): 미분 실행
- tensor.grad: 미분값을 확인할 수 있는 속성

In [3]:
import torch

In [11]:
x = torch.tensor([1.], requires_grad=True)
y = x ** 2
print(y)
print("미분 전:", x.grad)

# backward()는 기본적으로 한 번만 쓰고 그래프를 버린다
# 같은 그래프로 두 번째 역전파가 필요하면, y.backward(retain_graph=True)를 사용해야함
y.backward(retain_graph=True)
print("미분 후:", x.grad) # tensor([2.])

# x.grad.zero_(): 초기화 (초기화 하지 않으면 기본 누적됨)
x.grad.zero_()
z = 3 * y
print(z)

z.backward()
print("z 미분 후:", x.grad)


tensor([1.], grad_fn=<PowBackward0>)
미분 전: None
미분 후: tensor([2.])
tensor([3.], grad_fn=<MulBackward0>)
z 미분 후: tensor([6.])


In [13]:
# 체인룰
x = torch.tensor([1.], requires_grad=True)
a = x ** 2
b = a + 1
c = b ** 2
c.backward()
print(x.grad)

# 이 텐서를 계산 그래프에서 분리
result = x.grad.detach()
print(result.requires_grad)
print(result.item())

tensor([8.])
False
8.0


In [15]:
# 다변수 함수 이론
x = torch.tensor([1.], requires_grad=True)
y = torch.tensor([3.], requires_grad=True)
z = 2 * (x ** 2) + y ** 2
print(z)
z.backward()
print(x.grad)
print(y.grad)

tensor([11.], grad_fn=<AddBackward0>)
tensor([4.])
tensor([6.])


In [19]:
# with torch.no_grad():
# grad_fn 을 계산하고 싶지 않을 때 사용
# => 모델 훈련 후 test data를 가지고 평가할 때 사용

x = torch.tensor([1.], requires_grad=True)
with torch.no_grad():
    y = x ** 2
    print("with 안:", x.requires_grad)
    print(y)

print(x.requires_grad)
y = x ** 2
y.backward()



with 안: True
tensor([1.])
True
