## PyTorch Quiz 1 : Tensor 초기화

In [1]:
import torch

### 1. 빈 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x4 크기의 Tensor
- 값이 초기화되지 않은 상태

In [2]:
# 여기에 코드를 작성합니다
x = torch.empty(3, 4)
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


### 2. 0으로 채워진 Tensor 생성하기
다음과 같은 Tensor를 생성하세요.
- 2x5x3 크기의 Tensor
- 데이터 타입은 float64

In [3]:
# 여기에 코드를 작성합니다
x = torch.zeros(2, 5, 3, dtype=torch.double)
print(x)

tensor([[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]], dtype=torch.float64)


### 3. 1로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 4x4 크기의 Tensor
- 데이터 타입은 int

In [4]:
# 여기에 코드를 작성합니다
x = torch.ones(4, 4, dtype=torch.long)
print(x)

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])


### 4. 랜덤 값으로 채워진 Tensor 생성하기
다음 조건에 맞는 Tensor를 생성하세요.
- 3x3 크기의 Tensor
- 모든 값이 0과 1 사이의 랜덤 값

In [5]:
# 여기에 코드를 작성합니다
x = torch.rand(3,3)
print(x)

tensor([[0.7442, 0.4001, 0.3005],
        [0.0501, 0.6839, 0.0329],
        [0.9494, 0.7662, 0.6316]])


### 5. 다차원 Tensor 생성하기
다음과 같은 다차원 Tensor를 생성하세요.
- 값이 다음과 같은 2x3의 2D 배열
    ```
    [[1, 2, 3],
     [4, 5, 6]]
    ```

In [12]:
# 여기에 코드를 작성합니다
x = torch.tensor([[1,2,3],[4,5,6]])
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]])


### 6. Tensor의 값을 변경하기
1. 표준정규분포의 값을 랜덤으로 갖는 2x2 Tensor를 생성하세요.
2. 생성된 Tensor의 속성을 물려받은 원소가 0인 새로운 텐서를 만들어보세요. 

In [14]:
# 여기에 코드를 작성합니다
x = torch.randn(2,2)
print(x)
y = x.new_zeros(2, 2)
print(y)

tensor([[ 0.1278, -1.1261],
        [ 0.8511,  1.6194]])
tensor([[0., 0.],
        [0., 0.]])
